/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import cavalo.Utils;
import cavalo.Grafo;
import cavalo.Posicao;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author rafaelpaiva
 */
public class Tabuleiro extends javax.swing.JFrame {

    private int tamanho;
    Grafo grafo;

    /**
     * Creates new form Tabuleiro
     */
    public Tabuleiro() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCaminho = new javax.swing.JButton();
        jButtonTabela = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckFechado = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "null", "null", "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jButtonCaminho.setText("Gerar Caminho");
        jButtonCaminho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCaminhoMouseClicked(evt);
            }
        });

        jButtonTabela.setText("Gerar Tabela");
        jButtonTabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTabelaMouseClicked(evt);
            }
        });
        jButtonTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTabelaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tamanho:");

        jCheckFechado.setText("Fechado?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonTabela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCaminho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckFechado)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCaminho)
                    .addComponent(jButtonTabela)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jCheckFechado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTabelaActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_jButtonTabelaActionPerformed

    private void jButtonTabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTabelaMouseClicked
	Integer tamanho;
	try {
	    tamanho = Integer.parseInt(jTextField1.getText());
	} catch (Exception e) {
	    return;
	}
	if (tamanho < 0) {
	    return;
	}

	this.tamanho = tamanho;

	Object[][] data = new Object[tamanho][tamanho + 1];
	for (Object[] linha : data) {
	    for (Object elem : linha) {
		elem = null;
	    }
	}

	String[] linhas = new String[tamanho + 1];
	linhas[0] = "";
	for (int i = 1; i < linhas.length; i++) {
	    linhas[i] = Utils.getLetter(i);
	}

	jTable1.setModel(new javax.swing.table.DefaultTableModel(
	    data,
	    linhas
	) {
	    @Override
	    public Class getColumnClass(int columnIndex) {
		return java.lang.Integer.class;
	    }

	    @Override
	    public boolean isCellEditable(int rowIndex, int columnIndex) {
		return false;
	    }
	});

	for (int i = 1; i <= tamanho; i++) {
	    jTable1.setValueAt(i, i - 1, 0);
	}

	grafo = new Grafo(tamanho);
	Utils.popularGrafo(grafo);
    }//GEN-LAST:event_jButtonTabelaMouseClicked

    private void jButtonCaminhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCaminhoMouseClicked
	//List<Posicao> caminho = Utils.hamiltonianPath(grafo, new Posicao(tamanho/2, tamanho/2), jCheckFechado.isSelected());
	List<Posicao> caminho = Utils.hamiltonianPathOrCycle(grafo, jCheckFechado.isSelected());
	for (int i = 0; i < caminho.size(); i++) {
	    Posicao p = caminho.get(i);
	    jTable1.setValueAt(i + 1, p.getY(), p.getX() + 1);
	}
	
    }//GEN-LAST:event_jButtonCaminhoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Tabuleiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Tabuleiro().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCaminho;
    private javax.swing.JButton jButtonTabela;
    private javax.swing.JCheckBox jCheckFechado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
